/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bookshop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author SHEHAN
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Dashboard() {
        initComponents();
        setDateAndTime();
    }
    Dashboard(String text) {
        this();
        try {
                name.setText(text);
            
            ResultSet rs=MyDB.search("select type from login where username='"+text+"'");
            if (rs.next()) {
                type.setText(rs.getString("type"));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        one = new javax.swing.JPanel();
        user = new javax.swing.JButton();
        itemmanagement = new javax.swing.JButton();
        invoice = new javax.swing.JButton();
        user3 = new javax.swing.JButton();
        back2 = new javax.swing.JButton();
        two = new javax.swing.JPanel();
        addnewemployee = new javax.swing.JButton();
        search = new javax.swing.JButton();
        back = new javax.swing.JButton();
        three = new javax.swing.JPanel();
        newitem = new javax.swing.JButton();
        newitemtype = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        addreturnitem = new javax.swing.JButton();
        returnitem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        type1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        parent.setLayout(new java.awt.CardLayout());

        user.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        user.setText("User Management");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        itemmanagement.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        itemmanagement.setText("Item Management");
        itemmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmanagementActionPerformed(evt);
            }
        });

        invoice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        invoice.setText("Invoice");
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });

        user3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        user3.setText("Reports");
        user3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user3ActionPerformed(evt);
            }
        });

        back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dynamic_blue_left.png"))); // NOI18N
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout oneLayout = new javax.swing.GroupLayout(one);
        one.setLayout(oneLayout);
        oneLayout.setHorizontalGroup(
            oneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneLayout.createSequentialGroup()
                .addGroup(oneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oneLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(user)
                        .addGap(124, 124, 124)
                        .addComponent(itemmanagement)
                        .addGap(137, 137, 137)
                        .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oneLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(back2)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        oneLayout.setVerticalGroup(
            oneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(oneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemmanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(back2)
                .addGap(86, 86, 86))
        );

        parent.add(one, "card2");

        addnewemployee.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addnewemployee.setText("Add New Employee");
        addnewemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewemployeeActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        search.setText("Search and Edit");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dynamic_blue_left.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout twoLayout = new javax.swing.GroupLayout(two);
        two.setLayout(twoLayout);
        twoLayout.setHorizontalGroup(
            twoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(addnewemployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addComponent(search)
                .addGap(308, 308, 308))
            .addGroup(twoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        twoLayout.setVerticalGroup(
            twoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(twoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addnewemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(71, 71, 71))
        );

        parent.add(two, "card3");

        newitem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        newitem.setText("GRN");
        newitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newitemActionPerformed(evt);
            }
        });

        newitemtype.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        newitemtype.setText("New Item Type");
        newitemtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newitemtypeActionPerformed(evt);
            }
        });

        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dynamic_blue_left.png"))); // NOI18N
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        addreturnitem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addreturnitem.setText("Add Return Item");
        addreturnitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addreturnitemActionPerformed(evt);
            }
        });

        returnitem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        returnitem.setText("Return Item");
        returnitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnitemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout threeLayout = new javax.swing.GroupLayout(three);
        three.setLayout(threeLayout);
        threeLayout.setHorizontalGroup(
            threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threeLayout.createSequentialGroup()
                .addGroup(threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addreturnitem)
                    .addGroup(threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(threeLayout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(newitem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(229, 229, 229)
                            .addComponent(newitemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(threeLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(back1))))
                .addContainerGap(566, Short.MAX_VALUE))
            .addGroup(threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, threeLayout.createSequentialGroup()
                    .addContainerGap(838, Short.MAX_VALUE)
                    .addComponent(returnitem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(209, 209, 209)))
        );
        threeLayout.setVerticalGroup(
            threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threeLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newitem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newitemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(addreturnitem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(back1)
                .addGap(65, 65, 65))
            .addGroup(threeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(threeLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(returnitem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        parent.add(three, "card4");

        getContentPane().add(parent, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(622, 622, 622)
                .addComponent(jLabel1)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N
        jLabel4.setText("Logged in as :");

        type.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N

        type1.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N
        type1.setText("-");

        name.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N

        date.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        time.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        parent.removeAll();
        parent.add(two);
        parent.repaint();
        parent.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void itemmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmanagementActionPerformed
        parent.removeAll();
        parent.add(three);
        parent.repaint();
        parent.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemmanagementActionPerformed

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        Invoice i=new Invoice(name.getText());
        i.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceActionPerformed

    private void user3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user3ActionPerformed

    private void addnewemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewemployeeActionPerformed
        Employee e=new Employee();
        e.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_addnewemployeeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        SearchEmployee s=new SearchEmployee();
        s.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        parent.removeAll();
        parent.add(one);
        parent.repaint();
        parent.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void newitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newitemActionPerformed
        GRN i=new GRN(name.getText());
        i.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_newitemActionPerformed

    private void newitemtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newitemtypeActionPerformed
        ItemType i=new ItemType();
        i.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_newitemtypeActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        parent.removeAll();
        parent.add(one);
        parent.repaint();
        parent.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_back1ActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        Login l=new Login();
        l.setVisible(true);
        dispose();
        // TODO add your handling code hereAddReturnItem:
    }//GEN-LAST:event_back2ActionPerformed

    private void addreturnitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addreturnitemActionPerformed
        AddReturnItem r=new AddReturnItem(name.getText());
        r.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_addreturnitemActionPerformed

    private void returnitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnitemActionPerformed
        Return r=new Return(name.getText());
        r.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_returnitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewemployee;
    private javax.swing.JButton addreturnitem;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton back2;
    private javax.swing.JLabel date;
    private javax.swing.JButton invoice;
    private javax.swing.JButton itemmanagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel name;
    private javax.swing.JButton newitem;
    private javax.swing.JButton newitemtype;
    private javax.swing.JPanel one;
    private javax.swing.JPanel parent;
    private javax.swing.JButton returnitem;
    private javax.swing.JButton search;
    private javax.swing.JPanel three;
    private javax.swing.JLabel time;
    private javax.swing.JPanel two;
    private javax.swing.JLabel type;
    private javax.swing.JLabel type1;
    private javax.swing.JButton user;
    private javax.swing.JButton user3;
    // End of variables declaration//GEN-END:variables
Date d;
    SimpleDateFormat sdf;
    private void setDateAndTime() {
        Timer t=new Timer(1000, new ActionListener() {

            
                public void actionPerformed(ActionEvent e) {
                    d=new Date();
                    sdf=new SimpleDateFormat("yyyy-MM-dd");
                    date.setText(sdf.format(d));
                    sdf=new SimpleDateFormat("HH:mm:ss");
                    time.setText(sdf.format(d));
                }
            });
            t.start();
    }
}
