/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bookshop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SHEHAN
 */
public class GRN extends javax.swing.JFrame {

    /**
     * Creates new form Item
     */
    public GRN() {
        initComponents();
        getSupplier();
        getItem();
        jDialog2.setLocationRelativeTo(null);
        billid.grabFocus();
        getGRNID();
        getItemType();
        getItemID();
        jDialog1.setLocationRelativeTo(null);
        getBatchID();
        setDateAndTime();
    }

    GRN(String text) {
        this();
        try {
            name2.setText(text);
            ResultSet rs = MyDB.search("select type from login where username='" + text + "'");
            if (rs.next()) {
                type.setText(rs.getString("type"));
            }
        } catch (Exception e) {
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        refresh1 = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        type1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        itemid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        batchid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        newqty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        grnid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        itemtype = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        barcode = new javax.swing.JTextField();
        additemtype = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sprice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        billid = new javax.swing.JTextField();
        refreshitemtype = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        nettotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        payment = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        refresh2 = new javax.swing.JButton();
        s = new javax.swing.JButton();
        refresh3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        addsupplier = new javax.swing.JButton();
        supplier = new javax.swing.JComboBox();
        home = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(1050, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Batch ID", "Barcode", "Name", "Quantity", "Buying Price", "Selling Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel17.setText("Selling Price");

        jLabel18.setText("Name");

        name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name1KeyReleased(evt);
            }
        });

        refresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel17)
                .addGap(44, 44, 44)
                .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jLabel18)
                .addGap(47, 47, 47)
                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refresh1)
                .addGap(97, 97, 97))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refresh1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jDialog2.setMinimumSize(new java.awt.Dimension(850, 350));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Batch ID", "Barcode", "Name", "Quantity", "Buying Price", "Selling Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Item");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel19.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N
        jLabel19.setText("Logged in as :");

        type.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N

        type1.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N
        type1.setText("-");

        name2.setFont(new java.awt.Font("Simplified Arabic", 1, 20)); // NOI18N

        date.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        time.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel21.setText("GRN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 524, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("Item ID");

        itemid.setEditable(false);

        jLabel4.setText("Batch ID");

        batchid.setEditable(false);

        jLabel5.setText("Name");

        jLabel6.setText("Available Quantity");

        qty.setEditable(false);
        qty.setText("0");

        jLabel7.setText("New Quantity");

        newqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newqtyActionPerformed(evt);
            }
        });

        jLabel8.setText("GRN ID");

        grnid.setEditable(false);

        jLabel9.setText("Item Type");

        jLabel10.setText("Barcode");

        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });
        barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barcodeKeyReleased(evt);
            }
        });

        additemtype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        additemtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemtypeActionPerformed(evt);
            }
        });

        jLabel11.setText("Buying Price");

        bprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bpriceKeyTyped(evt);
            }
        });

        jLabel12.setText("Selling Price");

        sprice.setNextFocusableComponent(newqty);
        sprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spriceKeyTyped(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Batch ID", "Name", "Quantity", "Buying Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel13.setText("Supplier Bill ID");

        billid.setNextFocusableComponent(barcode);
        billid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                billidKeyReleased(evt);
            }
        });

        refreshitemtype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh-icon-0.png"))); // NOI18N
        refreshitemtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshitemtypeActionPerformed(evt);
            }
        });

        jLabel14.setText("Net Total");

        nettotal.setEditable(false);

        jLabel15.setText("Payment");

        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });

        jLabel16.setText("Balance");

        balance.setEditable(false);
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-xxl.png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        refresh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh-icon-0.png"))); // NOI18N
        refresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2ActionPerformed(evt);
            }
        });

        s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-3-xxl.png"))); // NOI18N
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        refresh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh-icon-0.png"))); // NOI18N
        refresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Supplier");

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh-icon-0.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        addsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        addsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsupplierActionPerformed(evt);
            }
        });

        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(bprice, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(299, 299, 299)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(batchid, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(31, 31, 31)
                                                    .addComponent(refresh2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addGap(40, 40, 40)
                                                    .addComponent(sprice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(62, 62, 62)
                                                    .addComponent(jLabel6)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(itemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(20, 20, 20)
                                                    .addComponent(additemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(refreshitemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7)
                                    .addGap(42, 42, 42)
                                    .addComponent(newqty, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(itemid)
                                            .addGap(18, 18, 18)
                                            .addComponent(refresh3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addGap(43, 43, 43))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(addsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(billid, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(s)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(grnid, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(66, 66, 66)
                        .addComponent(nettotal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(jLabel15)
                        .addGap(128, 128, 128)
                        .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(jLabel16)
                        .addGap(57, 57, 57)
                        .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(s, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(billid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(grnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(refresh)
                    .addComponent(addsupplier))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(additemtype)
                    .addComponent(refresh2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(batchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(itemtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refreshitemtype)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refresh3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(itemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(bprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(newqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nettotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(delete)
                        .addGap(192, 192, 192))))
        );

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MB__home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(home))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        barcode.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        name.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        qty.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        bprice.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        sprice.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        String i= jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        itemid.setText(i);
       String b= jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        batchid.setText(b);
        try {
            String x;
            ResultSet rs=MyDB.search("select * from itemtype where itemtypeid=(select itemtypeid from item where itemid='"+i+"' and batchid='"+b+"')");
            if (rs.next()) {
                x=rs.getString("itemtypeid")+" - "+rs.getString("itemtype");
                itemtype.setSelectedItem(x);
            }
        } catch (Exception e) {
        }
        jDialog1.setVisible(false);
        newqty.grabFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void addsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsupplierActionPerformed
        Supplier s=new Supplier();
        s.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addsupplierActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        getSupplier();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void additemtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemtypeActionPerformed
        ItemType i=new ItemType();
        i.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_additemtypeActionPerformed

    private void refreshitemtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshitemtypeActionPerformed
        getItemType();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshitemtypeActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if (evt.getKeyCode()==39) {
            billid.grabFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void billidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billidKeyReleased
         if (evt.getKeyCode()==39) {
            newqty.grabFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_billidKeyReleased

    private void newqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newqtyActionPerformed
        try {
            double b = Double.parseDouble(bprice.getText());
            double itemqty = Double.parseDouble(newqty.getText());
            
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            Vector v = new Vector();
            if (dtm.getRowCount() == 0) {
                v.add(itemid.getText());
                v.add(batchid.getText());
                v.add(name.getText());
                v.add(newqty.getText());
                v.add(bprice.getText());
                v.add(b * itemqty);
                dtm.addRow(v); 
                addToTable();
            }else{
                for (int j = 0; j < dtm.getRowCount(); j++) {
                    if (jTable2.getValueAt(j, 0).equals(itemid.getText()) & jTable2.getValueAt(j, 1).equals(batchid.getText())) {
                        String q = jTable2.getValueAt(j, 3).toString();
                        double finalqty = Double.parseDouble(q) + itemqty;
                        double finaltot = finalqty * b;
                        jTable2.setValueAt(finalqty, j, 3);
                        jTable2.setValueAt(finaltot, j, 5);
                       addToTable();
                        break;
                    } else if (j == dtm.getRowCount() - 1) {
                        v.add(itemid.getText());
                        v.add(batchid.getText());
                        v.add(name.getText());
                        v.add(newqty.getText());
                        v.add(bprice.getText());
                        v.add(b * itemqty);
                        dtm.addRow(v);
                        addToTable();
                        break;
                    }
                }
            }
           
            getItem();
            getItemID();
            getBatchID();
            clear();
             
            calNetTotal();
        } catch (Exception e) {
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_newqtyActionPerformed

    private void bpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bpriceKeyTyped
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bpriceKeyTyped

    private void spriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spriceKeyTyped
        
        // TODO add your handling code here:
    }//GEN-LAST:event_spriceKeyTyped

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        double d1=Double.parseDouble(payment.getText());
            double d2=Double.parseDouble(nettotal.getText());
            if(d1>=d2){
                balance.setText(""+(d1-d2));
                balance.grabFocus();
            } else{
                JOptionPane.showMessageDialog(payment, "Payment is not enough! ");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentActionPerformed

    
    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        try {
            Date d1 = new Date();
            String today = new SimpleDateFormat("yyyy-MM-dd").format(d1);
            String s=supplier.getSelectedItem().toString();
            s=s.split("-")[0];
            String e=null;
            ResultSet rs=MyDB.search("select * from login where username='"+name2.getText()+"'");
            if (rs.next()) {
                e=rs.getString("empid");
            }
            MyDB.iud("insert into grn values('"+grnid.getText()+"','"+today+"','"+nettotal.getText()+"','"+payment.getText()+"',"
                    + "'"+balance.getText()+"','"+s+"','"+billid.getText()+"','"+e+"')");
            DefaultTableModel dtm=(DefaultTableModel)jTable2.getModel();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                String s1=dtm.getValueAt(i, 0).toString();
                String s2=dtm.getValueAt(i, 1).toString();
                String s3=dtm.getValueAt(i, 3).toString();
                String s4=dtm.getValueAt(i, 5).toString();
                MyDB.iud("insert into grnitem (grnid, itemid,batchid, qty,total) values ('"+grnid.getText()+"','"+s1+"','"+s2+"','"+s3+"','"+s4+"')");
                
            }
            clear();
            billid.setText(null);
            dtm.setRowCount(0);
            getGRNID();
            getItem();
            getBatchID();
            payment.setText(null);
            nettotal.setText(null);
            balance.setText(null);
        } catch (Exception e) {
          e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        String s = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        String s1 = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
        itemid.setText(s);
        batchid.setText(s1);
        name.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        newqty.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        bprice.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        try {
            ResultSet rs = MyDB.search("select * from item inner join batch where itemid='" + s + "' and item.batchid='" + s1 + "' "
                    + "and item.batchid=batch.batchid");
            if (rs.next()) {
                barcode.setText(rs.getString("barcode"));
                sprice.setText(rs.getString("sprice"));
                qty.setText(rs.getString("qty"));
            }
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void refresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2ActionPerformed
        getBatchID();
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh2ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Dashboard d=new Dashboard();
        d.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        jDialog1.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_sActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
            ResultSet rs = MyDB.search("select * from item inner join batch where item.batchid=batch.batchid and barcode='" + barcode.getText() + "'");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("itemid"));
                v.add(rs.getString(2));
                v.add(rs.getString("barcode"));
                v.add(rs.getString("name"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("bprice"));
                v.add(rs.getString("sprice"));
                dtm.addRow(v);
                jDialog2.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_barcodeActionPerformed

    private void name1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name1KeyReleased
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            ResultSet rs;
            if (price1.getText().isEmpty()) {
                rs = MyDB.search("select * from item inner join batch where item.batchid=batch.batchid and  name like '%" + name1.getText() + "%'");
                dtm.setRowCount(0);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("itemid"));
                    v.add(rs.getString(2));
                    v.add(rs.getString("barcode"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("qty"));
                    v.add(rs.getString("bprice"));
                    v.add(rs.getString("sprice"));
                    dtm.addRow(v);
                }
            } else {
                rs = MyDB.search("select * from item inner join batch where item.batchid=batch.batchid  and sprice='" + price1.getText() + "' and name"
                    + " like '%" + name1.getText() + "%'");
                dtm.setRowCount(0);
                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("itemid"));
                    v.add(rs.getString(2));
                    v.add(rs.getString("barcode"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("qty"));
                    v.add(rs.getString("bprice"));
                    v.add(rs.getString("sprice"));
                    dtm.addRow(v);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_name1KeyReleased

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        getItem();
        name1.setText(null);
        price1.setText(null);
        price1.grabFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        String i= jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
        itemid.setText(i);
       String b= jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString();
        batchid.setText(b);
        barcode.setText(jTable3.getValueAt(jTable3.getSelectedRow(), 2).toString());
        name.setText(jTable3.getValueAt(jTable3.getSelectedRow(), 3).toString());
        qty.setText(jTable3.getValueAt(jTable3.getSelectedRow(), 4).toString());
        bprice.setText(jTable3.getValueAt(jTable3.getSelectedRow(), 5).toString());
        sprice.setText(jTable3.getValueAt(jTable3.getSelectedRow(), 6).toString());
       
        try {
            String x;
            ResultSet rs=MyDB.search("select * from itemtype where itemtypeid=(select itemtypeid from item where itemid='"+i+"' and batchid='"+b+"')");
            if (rs.next()) {
                x=rs.getString("itemtypeid")+" - "+rs.getString("itemtype");
                itemtype.setSelectedItem(x);
            }
        } catch (Exception e) {
        }
        jDialog2.setVisible(false);
        newqty.grabFocus();
    }//GEN-LAST:event_jTable3MouseClicked

    private void barcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeKeyReleased
         if (evt.getKeyCode()==40) {
            payment.grabFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeKeyReleased

    private void refresh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh3ActionPerformed
        getItemID();
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh3ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            int x = jTable2.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.removeRow(x);
            MyDB.iud("update item set qty='"+qty.getText()+"'-'"+newqty.getText()+"' where itemid='"+itemid.getText()+"' and batchid='"+batchid.getText()+"'");
            DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            getItem();
            getItemID();
            getBatchID();
            calNetTotal();
            clear();
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        billid.grabFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GRN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additemtype;
    private javax.swing.JButton addsupplier;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField barcode;
    private javax.swing.JTextField batchid;
    private javax.swing.JTextField billid;
    private javax.swing.JTextField bprice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel date;
    private javax.swing.JButton delete;
    private javax.swing.JTextField grnid;
    private javax.swing.JButton home;
    private javax.swing.JTextField itemid;
    private javax.swing.JComboBox itemtype;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JLabel name2;
    private javax.swing.JTextField nettotal;
    private javax.swing.JTextField newqty;
    private javax.swing.JTextField payment;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField qty;
    private javax.swing.JButton refresh;
    private javax.swing.JButton refresh1;
    private javax.swing.JButton refresh2;
    private javax.swing.JButton refresh3;
    private javax.swing.JButton refreshitemtype;
    private javax.swing.JButton s;
    private javax.swing.JTextField sprice;
    private javax.swing.JComboBox supplier;
    private javax.swing.JLabel time;
    private javax.swing.JLabel type;
    private javax.swing.JLabel type1;
    // End of variables declaration//GEN-END:variables

    public void getSupplier() {
        try {
            ResultSet rs=MyDB.search("select * from supplier");
            Vector v=new Vector();
            while (rs.next()) {                
                v.add(rs.getString("supplierid")+" - "+rs.getString("name"));
                supplier.setModel(new DefaultComboBoxModel(v));
            }
        } catch (Exception e) {
        }
    }

    private void getItem() {
        try {
            DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
            ResultSet rs=MyDB.search("select * from item inner join batch where item.batchid=batch.batchid");
            dtm.setRowCount(0);
            while (rs.next()) {                
                Vector v=new Vector();
                v.add(rs.getString("itemid"));
                v.add(rs.getString(2));
                v.add(rs.getString("barcode"));
                v.add(rs.getString("name"));
                v.add(rs.getString("qty"));
                v.add(rs.getString("bprice"));
                v.add(rs.getString("sprice"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }

    private void getGRNID() {
        try {
            ResultSet rs=MyDB.search("select count(grnid) as x from grn");
            if (rs.next()) {
                int x=Integer.parseInt(rs.getString("x"));
                ++x;
                grnid.setText("G"+x);
            }
        } catch (Exception e) {
        }
    }

    private void getItemType() {
        try {
            ResultSet rs=MyDB.search("select * from itemtype");
            Vector v=new Vector();
            while (rs.next()) {                
                v.add(rs.getString("itemtypeid")+" - "+rs.getString("itemtype"));
                itemtype.setModel(new DefaultComboBoxModel(v));
            }
        } catch (Exception e) {
        }
    }

    private void getItemID() {
         try {
            ResultSet rs=MyDB.search("select count(itemid) as x from item");
            if (rs.next()) {
                int x=Integer.parseInt(rs.getString("x"));
                ++x;
                itemid.setText("I"+x);
            }
        } catch (Exception e) {
        }
    }

    private void getBatchID() {
         try {
            ResultSet rs=MyDB.search("select count(batchid) as x from batch");
            if (rs.next()) {
                int x=Integer.parseInt(rs.getString("x"));
                ++x;
                batchid.setText("B"+x);
            }
        } catch (Exception e) {
        }
    }

    private void addToTable() {
        try {
            String i=itemtype.getSelectedItem().toString();
            i = i.split("-")[0];
             ResultSet rs = MyDB.search("select * from item where itemid='" + itemid.getText() + "' and batchid='" + batchid.getText() + "'");
                if (rs.next()) {
                    MyDB.iud("update item set qty=qty+'" + newqty.getText() + "' where itemid='" + itemid.getText() + "' and "
                            + "batchid='" + batchid.getText() + "'");
                } else {
                    MyDB.iud("insert into batch values('" + batchid.getText() + "','" + bprice.getText() + "','" + sprice.getText() + "')");
                    MyDB.iud("insert into item values('" + itemid.getText() + "','" + batchid.getText() + "','" + name.getText() + "',"
                            + "'" + newqty.getText() + "','" + i + "','" + barcode.getText() + "')");
                }
        } catch (Exception e) {
        }
    }

    private void calNetTotal() {
        DefaultTableModel dtm=(DefaultTableModel)jTable2.getModel();
         double stot=0;
         for (int i = 0; i < dtm.getRowCount(); i++) {
            String s1=dtm.getValueAt(i, 5).toString();
            stot+=Double.parseDouble(s1);
         
         }
         nettotal.setText(""+stot);
    }

    private void clear() {
        barcode.grabFocus();
            itemtype.setSelectedIndex(0);
            name.setText(null);
            bprice.setText(null);
            barcode.setText(null);
            sprice.setText(null);
            qty.setText(null);
            newqty.setText(null);
          
    }
 Date d;
    SimpleDateFormat sdf;
    private void setDateAndTime() {
        Timer t=new Timer(1000, new ActionListener() {

            
                public void actionPerformed(ActionEvent e) {
                    d=new Date();
                    sdf=new SimpleDateFormat("yyyy-MM-dd");
                    date.setText(sdf.format(d));
                    sdf=new SimpleDateFormat("HH:mm:ss");
                    time.setText(sdf.format(d));
                }
            });
            t.start();
    }
}
